//! End-to-end parity tests between litmus (Rust) and collimator (Python).
//!
//! Tests the full pipeline: cleave JSON → feature extraction → standardization
//! → model prediction → threshold classification. Catches any divergence in
//! finding parsing, path extraction, metric aggregation, standardization,
//! model inference, or threshold application.
//!
//! The fixture is generated by collimator's `generate_extraction_fixture`.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use litmus::features::{ExtractContext, FeatureSpec};
use litmus::model::Model;

/// Resolve the model directory: LITMUS_MODELS_DIR env var, or fallback to
/// ../collimator/out (co-located development layout).
fn model_dir() -> std::path::PathBuf {
    std::env::var("LITMUS_MODELS_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| {
            std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../collimator/out"))
        })
}

#[derive(serde::Deserialize)]
struct ExtractionFixture {
    n_features: usize,
    #[serde(default)]
    feature_names: Vec<String>,
    samples: Vec<ExtractionSample>,
}

#[derive(serde::Deserialize)]
struct ExtractionSample {
    report: serde_json::Value,
    expected_features: Vec<f32>,
    #[serde(default)]
    expected_standardized: Option<Vec<f32>>,
    #[serde(default)]
    expected_probability: Option<f64>,
    #[serde(default)]
    expected_classification: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    threshold: Option<f64>,
}

fn load_fixture() -> Option<ExtractionFixture> {
    let path = model_dir().join("extraction_fixture.json");
    if !path.exists() {
        return None;
    }
    let data = std::fs::read_to_string(&path).expect("read extraction fixture");
    Some(serde_json::from_str(&data).expect("parse extraction fixture"))
}

fn load_spec() -> Option<FeatureSpec> {
    let path = model_dir().join("feature_spec.json");
    if !path.exists() {
        return None;
    }
    Some(FeatureSpec::load(&path).expect("load feature spec"))
}

/// Test 1: raw feature extraction parity.
#[test]
fn feature_extraction_matches_collimator() {
    let Some(fixture) = load_fixture() else {
        eprintln!(
            "SKIPPED: extraction_fixture.json not found — run `make train` or `make fixture` in collimator"
        );
        return;
    };
    let Some(spec) = load_spec() else {
        eprintln!("SKIPPED: feature_spec.json not found");
        return;
    };

    assert_eq!(
        spec.total_features(),
        fixture.n_features,
        "feature spec has {} features but fixture expects {}",
        spec.total_features(),
        fixture.n_features,
    );

    // Verify feature name ordering matches between litmus and Python.
    // This catches offset bugs (e.g., adding features to agg without
    // updating litmus offsets) with a clear error message.
    if !fixture.feature_names.is_empty() {
        let rust_names = spec.feature_names();
        let n = rust_names.len().min(fixture.feature_names.len());
        for j in 0..n {
            assert_eq!(
                rust_names[j], fixture.feature_names[j],
                "feature name mismatch at index {j}: \
                 rust={:?} python={:?} — likely an offset bug in litmus",
                rust_names[j], fixture.feature_names[j],
            );
        }
    }

    let ctx = ExtractContext::new(&spec);

    for (i, sample) in fixture.samples.iter().enumerate() {
        let rust_features = ctx.extract(&sample.report);

        assert_eq!(
            rust_features.len(),
            sample.expected_features.len(),
            "sample {i}: feature vector length mismatch"
        );

        // Collect ALL diverging features, not just the worst one.
        let mut divergences: Vec<(usize, f32, f32, f32)> = Vec::new();
        for (j, (&rust_val, &python_val)) in rust_features
            .iter()
            .zip(sample.expected_features.iter())
            .enumerate()
        {
            let diff = (rust_val - python_val).abs();
            if diff > 1e-5 {
                divergences.push((j, rust_val, python_val, diff));
            }
        }

        if !divergences.is_empty() {
            divergences.sort_by(|a, b| b.3.partial_cmp(&a.3).unwrap());
            let mut msg = format!(
                "sample {i}: {n} features diverge (showing up to 10):\n",
                n = divergences.len()
            );
            for &(j, rust_val, python_val, diff) in divergences.iter().take(10) {
                let name = if j < fixture.feature_names.len() {
                    fixture.feature_names[j].as_str()
                } else {
                    "?"
                };
                msg.push_str(&format!(
                    "  [{j}] {name}: rust={rust_val:.6} python={python_val:.6} diff={diff:.2e}\n"
                ));
            }
            panic!("{msg}");
        }
    }
}

/// Test 2: full pipeline parity (extract → standardize → predict → classify).
#[test]
fn full_pipeline_matches_collimator() {
    let Some(fixture) = load_fixture() else {
        eprintln!("SKIPPED: extraction_fixture.json not found");
        return;
    };

    // Skip if fixture doesn't have end-to-end data.
    let has_e2e = fixture
        .samples
        .first()
        .is_some_and(|s| s.expected_probability.is_some());
    if !has_e2e {
        eprintln!(
            "SKIPPED: extraction_fixture.json has no end-to-end data (regenerate with model)"
        );
        return;
    }

    let dir = model_dir();
    let Some(spec) = load_spec() else {
        eprintln!("SKIPPED: feature_spec.json not found");
        return;
    };
    let model = Model::load(&dir, None).expect("failed to load model");
    let ctx = ExtractContext::new(&spec);

    for (i, sample) in fixture.samples.iter().enumerate() {
        // Step 1: extract raw features.
        let mut features = ctx.extract(&sample.report);

        // Step 2: standardize.
        spec.standardize(&mut features);

        // Verify standardized features match Python.
        if let Some(ref expected_std) = sample.expected_standardized {
            let mut divergences: Vec<(usize, f32, f32, f32)> = Vec::new();
            for (j, (&rust_val, &python_val)) in
                features.iter().zip(expected_std.iter()).enumerate()
            {
                let diff = (rust_val - python_val).abs();
                if diff > 1e-4 {
                    divergences.push((j, rust_val, python_val, diff));
                }
            }
            if !divergences.is_empty() {
                divergences.sort_by(|a, b| b.3.partial_cmp(&a.3).unwrap());
                let mut msg = format!(
                    "sample {i}: standardization — {n} features diverge:\n",
                    n = divergences.len()
                );
                for &(j, rv, pv, diff) in divergences.iter().take(10) {
                    let name = fixture.feature_names.get(j).map(|s| s.as_str()).unwrap_or("?");
                    msg.push_str(&format!(
                        "  [{j}] {name}: rust={rv:.6} python={pv:.6} diff={diff:.2e}\n"
                    ));
                }
                panic!("{msg}");
            }
        }

        // Step 3: predict.
        let (probability, classification) = model.predict(&features).expect("predict failed");

        // Verify probability matches Python (dense inference, same code path).
        if let Some(expected_prob) = sample.expected_probability {
            let diff = (f64::from(probability) - expected_prob).abs();
            assert!(
                diff < 5e-3,
                "sample {i}: probability diverges — rust={probability:.8} python={expected_prob:.8} diff={diff:.2e}"
            );
        }

        // Step 4: verify classification matches Python.
        if let Some(ref expected_class) = sample.expected_classification {
            let rust_class = format!("{classification}");
            assert_eq!(
                rust_class, *expected_class,
                "sample {i}: classification diverges — rust={rust_class} python={expected_class} \
                 (rust_prob={probability:.6})"
            );
        }
    }
}
