//! End-to-end parity tests between litmus (Rust) and collimator (Python).
//!
//! Tests the full pipeline: cleave JSON → feature extraction → standardization
//! → model prediction → threshold classification. Catches any divergence in
//! finding parsing, path extraction, metric aggregation, standardization,
//! model inference, or threshold application.
//!
//! The fixture is generated by collimator's `generate_extraction_fixture`.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use scan::features::{ExtractContext, FeatureSpec};
use scan::model::Model;

/// Resolve the model directory: SCAN_MODELS_DIR env var, or fallback to
/// ../collimator/out (co-located development layout).
fn model_dir() -> std::path::PathBuf {
    std::env::var("SCAN_MODELS_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| {
            std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../collimator/out"))
        })
}

#[derive(serde::Deserialize)]
struct ExtractionFixture {
    n_features: usize,
    #[serde(default)]
    feature_names: Vec<String>,
    samples: Vec<ExtractionSample>,
}

#[derive(serde::Deserialize)]
struct ExtractionSample {
    report: serde_json::Value,
    expected_features: Vec<f32>,
    #[serde(default)]
    expected_standardized: Option<Vec<f32>>,
    #[serde(default)]
    expected_probability: Option<f64>,
    #[serde(default)]
    expected_classification: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    threshold: Option<f64>,
}

fn load_fixture() -> Option<ExtractionFixture> {
    let path = model_dir().join("extraction_fixture.json");
    if !path.exists() {
        return None;
    }
    let data = std::fs::read_to_string(&path).expect("read extraction fixture");
    Some(serde_json::from_str(&data).expect("parse extraction fixture"))
}

fn load_spec() -> Option<FeatureSpec> {
    let path = model_dir().join("feature_spec.json");
    if !path.exists() {
        return None;
    }
    // Skip (rather than fail) when the on-disk collimator bundle is stale —
    // e.g. an older feature-spec ABI than this litmus build requires.
    match FeatureSpec::load(&path) {
        Ok(spec) => Some(spec),
        Err(e) => {
            eprintln!(
                "skipping extraction parity: {} unusable: {e}",
                path.display()
            );
            None
        }
    }
}

/// Test 1: raw feature extraction parity.
#[test]
fn feature_extraction_matches_collimator() {
    let Some(fixture) = load_fixture() else {
        eprintln!(
            "SKIPPED: extraction_fixture.json not found — run `make train` or `make fixture` in collimator"
        );
        return;
    };
    let Some(spec) = load_spec() else {
        eprintln!("SKIPPED: feature_spec.json not found");
        return;
    };

    assert_eq!(
        spec.total_features(),
        fixture.n_features,
        "feature spec has {} features but fixture expects {}",
        spec.total_features(),
        fixture.n_features,
    );

    // Verify feature name ordering matches between litmus and Python.
    // This catches offset bugs (e.g., adding features to agg without
    // updating litmus offsets) with a clear error message.
    if !fixture.feature_names.is_empty() {
        let rust_names = spec.feature_names();
        for (j, (rust_name, python_name)) in rust_names
            .iter()
            .zip(fixture.feature_names.iter())
            .enumerate()
        {
            assert_eq!(
                rust_name, python_name,
                "feature name mismatch at index {j}: \
                 rust={rust_name:?} python={python_name:?} — likely an offset bug in litmus",
            );
        }
    }

    let ctx = ExtractContext::new(&spec);

    for (i, sample) in fixture.samples.iter().enumerate() {
        let rust_features = ctx.extract(&sample.report);

        assert_eq!(
            rust_features.len(),
            sample.expected_features.len(),
            "sample {i}: feature vector length mismatch"
        );

        // Collect ALL diverging features, not just the worst one.
        let mut divergences: Vec<(usize, f32, f32, f32)> = Vec::new();
        for (j, (&rust_val, &python_val)) in rust_features
            .iter()
            .zip(sample.expected_features.iter())
            .enumerate()
        {
            let diff = (rust_val - python_val).abs();
            if diff > 1e-5 {
                divergences.push((j, rust_val, python_val, diff));
            }
        }

        if !divergences.is_empty() {
            divergences.sort_by(|a, b| b.3.partial_cmp(&a.3).unwrap());
            let mut msg = format!(
                "sample {i}: {n} features diverge (showing up to 10):\n",
                n = divergences.len()
            );
            for &(j, rust_val, python_val, diff) in divergences.iter().take(10) {
                let name = if j < fixture.feature_names.len() {
                    fixture.feature_names[j].as_str()
                } else {
                    "?"
                };
                msg.push_str(&format!(
                    "  [{j}] {name}: rust={rust_val:.6} python={python_val:.6} diff={diff:.2e}\n"
                ));
            }
            assert!(divergences.is_empty(), "{msg}");
        }
    }
}

/// Test 2: full pipeline parity (extract → standardize → predict → classify).
#[test]
fn full_pipeline_matches_collimator() {
    let Some(fixture) = load_fixture() else {
        eprintln!("SKIPPED: extraction_fixture.json not found");
        return;
    };

    // Skip if fixture doesn't have end-to-end data.
    let has_e2e = fixture
        .samples
        .first()
        .is_some_and(|s| s.expected_probability.is_some());
    if !has_e2e {
        eprintln!(
            "SKIPPED: extraction_fixture.json has no end-to-end data (regenerate with model)"
        );
        return;
    }

    let dir = model_dir();
    let Some(spec) = load_spec() else {
        eprintln!("SKIPPED: feature_spec.json not found");
        return;
    };
    let model = Model::load(&dir, None, None).expect("failed to load model");
    let ctx = ExtractContext::new(&spec);

    for (i, sample) in fixture.samples.iter().enumerate() {
        // Step 1: extract raw features.
        let mut features = ctx.extract(&sample.report);

        // Step 2: standardize.
        spec.standardize(&mut features);

        // Verify standardized features match Python.
        if let Some(ref expected_std) = sample.expected_standardized {
            let mut divergences: Vec<(usize, f32, f32, f32)> = Vec::new();
            for (j, (&rust_val, &python_val)) in
                features.iter().zip(expected_std.iter()).enumerate()
            {
                let diff = (rust_val - python_val).abs();
                if diff > 1e-4 {
                    divergences.push((j, rust_val, python_val, diff));
                }
            }
            if !divergences.is_empty() {
                divergences.sort_by(|a, b| b.3.partial_cmp(&a.3).unwrap());
                let mut msg = format!(
                    "sample {i}: standardization — {n} features diverge:\n",
                    n = divergences.len()
                );
                for &(j, rv, pv, diff) in divergences.iter().take(10) {
                    let name = fixture.feature_names.get(j).map_or("?", String::as_str);
                    msg.push_str(&format!(
                        "  [{j}] {name}: rust={rv:.6} python={pv:.6} diff={diff:.2e}\n"
                    ));
                }
                assert!(divergences.is_empty(), "{msg}");
            }
        }

        // Step 3: predict.
        let (probability, classification) = model.predict(&features).expect("predict failed");

        // Verify probability matches Python (dense inference, same code path).
        if let Some(expected_prob) = sample.expected_probability {
            let diff = (f64::from(probability) - expected_prob).abs();
            assert!(
                diff < 5e-3,
                "sample {i}: probability diverges — rust={probability:.8} python={expected_prob:.8} diff={diff:.2e}"
            );
        }

        // Step 4: verify classification matches Python.
        if let Some(ref expected_class) = sample.expected_classification {
            let rust_class = format!("{classification}");
            assert_eq!(
                rust_class, *expected_class,
                "sample {i}: classification diverges — rust={rust_class} python={expected_class} \
                 (rust_prob={probability:.6})"
            );
        }
    }
}

/// Test 3: per-route extraction parity for the *new* feature families.
///
/// Walks `SCAN_MODELS_DIR/{filetypes,filegroups}/*/feature_spec.json` and
/// validates extraction parity against any per-route `extraction_fixture.json`
/// that sits next to it. Per-route fixtures are generated by
/// `collimator/scripts/gen_route_extraction_fixture.py`.
///
/// Scope is intentionally narrowed to the families introduced for v17:
/// `kv:`, `symbol:`, `symbol_bi:`, `symbol_tri:`, `textenc:`,
/// `metrics:derived_*`, `struct:silent_packer_signal`, and
/// `agg:suspicious_{bi,tri}gram_count`. Per-route specs expose a separate
/// long-standing extraction divergence in `bigrams:`/`trigram:`/
/// `unsigned_bigram:` features that this task is not in scope to fix —
/// see the divergence_audit test for the family-by-family picture.
#[test]
fn per_route_feature_extraction_matches_collimator() {
    /// Families covered by the v17 family port. Anything outside this list
    /// is treated as out-of-scope here (see audit test).
    fn is_in_scope(name: &str) -> bool {
        name.starts_with("kv:")
            || name.starts_with("symbol:")
            || name.starts_with("symbol_bi:")
            || name.starts_with("symbol_tri:")
            || name.starts_with("textenc:")
            || name.starts_with("metrics:derived_")
            || name == "struct:silent_packer_signal"
            || name == "agg:suspicious_bigram_count"
            || name == "agg:suspicious_trigram_count"
    }

    let dir = model_dir();
    let mut routes_checked = 0usize;
    let mut routes_skipped = 0usize;
    let mut total_samples = 0usize;
    let mut family_hits: std::collections::BTreeMap<&'static str, usize> =
        std::collections::BTreeMap::new();

    for parent in ["filetypes", "filegroups"] {
        let parent_dir = dir.join(parent);
        let Ok(entries) = std::fs::read_dir(&parent_dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let route_dir = entry.path();
            if !route_dir.is_dir() {
                continue;
            }
            let spec_path = route_dir.join("feature_spec.json");
            let fixture_path = route_dir.join("extraction_fixture.json");
            if !spec_path.exists() || !fixture_path.exists() {
                routes_skipped += 1;
                continue;
            }
            let spec = FeatureSpec::load(&spec_path)
                .unwrap_or_else(|e| panic!("load spec for {}: {e}", route_dir.display()));
            let fixture_data = std::fs::read_to_string(&fixture_path)
                .unwrap_or_else(|e| panic!("read {}: {e}", fixture_path.display()));
            let fixture: ExtractionFixture = serde_json::from_str(&fixture_data)
                .unwrap_or_else(|e| panic!("parse {}: {e}", fixture_path.display()));

            assert_eq!(
                spec.total_features(),
                fixture.n_features,
                "{}: spec has {} features, fixture {}",
                route_dir.display(),
                spec.total_features(),
                fixture.n_features,
            );

            // Tally which new families this route exercises, so the test
            // output makes it obvious whether kv/symbol/textenc are actually
            // being validated and not just trivially absent.
            for fname in spec.feature_names() {
                for fam in [
                    "kv:",
                    "symbol_bi:",
                    "symbol_tri:",
                    "symbol:",
                    "textenc:",
                    "metrics:derived_",
                ] {
                    if fname.starts_with(fam) {
                        *family_hits.entry(fam).or_default() += 1;
                        break;
                    }
                }
                if fname == "agg:suspicious_bigram_count"
                    || fname == "agg:suspicious_trigram_count"
                    || fname == "struct:silent_packer_signal"
                {
                    *family_hits.entry("fixed_fills").or_default() += 1;
                }
            }

            let ctx = ExtractContext::new(&spec);
            for (i, sample) in fixture.samples.iter().enumerate() {
                let rust_features = ctx.extract(&sample.report);
                assert_eq!(
                    rust_features.len(),
                    sample.expected_features.len(),
                    "{}: sample {i}: length mismatch",
                    route_dir.display(),
                );
                let mut divergences: Vec<(usize, f32, f32, f32)> = Vec::new();
                for (j, (&rust_val, &python_val)) in rust_features
                    .iter()
                    .zip(sample.expected_features.iter())
                    .enumerate()
                {
                    let diff = (rust_val - python_val).abs();
                    if diff > 1e-5 {
                        let name = spec.feature_names().get(j).map_or("?", String::as_str);
                        if !is_in_scope(name) {
                            continue;
                        }
                        divergences.push((j, rust_val, python_val, diff));
                    }
                }
                if !divergences.is_empty() {
                    divergences.sort_by(|a, b| b.3.partial_cmp(&a.3).unwrap());
                    let mut msg = format!(
                        "{}: sample {i}: {n} in-scope features diverge (top 10):\n",
                        route_dir.display(),
                        n = divergences.len()
                    );
                    for &(j, rv, pv, diff) in divergences.iter().take(10) {
                        let name = spec.feature_names().get(j).map_or("?", String::as_str);
                        msg.push_str(&format!(
                            "  [{j}] {name}: rust={rv:.6} python={pv:.6} diff={diff:.2e}\n"
                        ));
                    }
                    panic!("{msg}");
                }
            }
            routes_checked += 1;
            total_samples += fixture.samples.len();
        }
    }

    if routes_checked == 0 {
        eprintln!(
            "SKIPPED: no per-route extraction_fixture.json files found under {}/{{filetypes,filegroups}}/*/. \
             Run `python scripts/gen_route_extraction_fixture.py --route <route>` in collimator to create one.",
            dir.display()
        );
        return;
    }
    eprintln!(
        "per-route parity: {routes_checked} routes ok ({total_samples} samples); \
         {routes_skipped} routes had no fixture"
    );
    if !family_hits.is_empty() {
        eprintln!("  feature-family coverage (total slot count across routes):");
        for (fam, count) in &family_hits {
            eprintln!("    {fam:<18} {count}");
        }
    }
}
